apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}