apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-svc
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.server.service.port }} # 80 how nginx talks to this service
      targetPort: {{ .Values.server.service.targetPort }} #8000 container port in deployment

      #