name: Build and push Docker images 
on:
  push:
    branches: [main, cicd, 'release/*']
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Debug secret
        
        run: |
              if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
                echo "DOCKER_USERNAME is not set";
              else
                echo "DOCKER_USERNAME is set";
              fi
        #echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME }}" | sed 's/./&/g'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker image tag
        id: tag
        # dont add space after = sign in variable assignment 
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD) # Get the short SHA of the commit
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT # Set output variable
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV # Set environment variable
          echo "Image tag: ${SHORT_SHA}"


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push image to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          # always reference the example tool to know the right keys to use
          tags: ${{ secrets.DOCKER_USERNAME }}/fastapi3tier:${{steps.tag.outputs.tag}}

        
      - name: Update Helm Values with image tag
        run: |
          echo "Updating Helm chart values with new image tag..."
          sed -i 's|repository: .*|repository: '"${{ secrets.DOCKER_USERNAME }}/flaskapp"'|g' ./charts/app/values.yaml
          sed -i 's|tag: .*|tag: ${{steps.tag.outputs.tag}}|g' ./charts/app/values.yaml
          cat ./charts/app/values.yaml

      - name: Commit and push Helm chart changes
        run: |
          git config --global user.name "perolasanta"
          git config --global user.email "peteroebello@gmail.com "
          git add ./charts/app/values.yaml
          git commit -m "Update Helm chart with new Docker image tag:
          ${{steps.tag.outputs.tag}}" || echo "No changes to commit"
          git push origin HEAD # push to current branch

          